version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
            apt-get -y update && apt-get -y upgrade && apt-get -y install ca-certificates && apt-get -y install rename
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive && apt-get -y update && apt-get -y upgrade && apt-get -y install tzdata git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 wget python3 python3-pip python gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata
            python3 -m pip  install networkx
            git config --global user.name "ビクセル"
            git config --global user.email "vcyzscape@gmail.com"
            git clone https://GITHUB_TOKEN@github.com/vcyzteen/TEA-PROJECT
            cd TEA-PROJECT
            git checkout EAS
            git reset --hard 38937466a7f87b475f1913a409b52c8d46a29b5b
            git cherry-pick 46c89a5489ad11dbdedcf17340064e5df471cfc0 46c89a5489ad11dbdedcf17340064e5df471cfc0 fb182f885d566e8a49638232fd118accfcb03f11 e1300bd3638b17fc4d8229310b7c79c372643312 887429364acba67f68c0fb2fd30c393d83375d58 ca63c2b2c27a7954e09606725f2232e44816f164
            git push https://GITHUB_TOKEN@github.com/vcyzteen/TEA-PROJECT.git
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
