version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
            apt-get -y update && apt-get -y upgrade && apt-get -y install ca-certificates && apt-get -y install rename
      - run:
          command: |
            export DEBIAN_FRONTEND=noninteractive && apt-get -y update && apt-get -y upgrade && apt-get -y install tzdata git automake lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng bc libstdc++6 wget python3 python3-pip python gcc clang libssl-dev rsync flex git-lfs libz3-dev libz3-4 axel
            ln -fs /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata
            python3 -m pip  install networkx
            git config --global user.name "Calliope-K"
            git config --global user.email "firsname76@gmail.com"
            git clone https://github.com/Calliope-K/Tea-Toolchain -b ARM64
            cd aarch64-linux-android-4.9
            cd bin
            rename 's/921d9846-a815-11e9-84ea-ff8bce1b90b6/GCC-4.9-Tea-Project/' 921d9846-a815-11e9-84ea-ff8bce1b90b6
            git add .
            git commit -m Tea-Project --signoff
            git push https://$GITHUB_TOKEN@github.com/Calliope-K/Tea-Toolchain.git
          no_output_timeout : 5h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile 
